In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('person_2016')

In [3]:
df.head()

,state_number,consecutive_number,number_of_motor_vehicles_in_transport_mvit,vehicle_number,person_number,number_of_motor_vehicle_striking_non_motorist,county,day_of_crash,month_of_crash,hour_of_crash,...,related_factors_person_level2,related_factors_person_level3,fatal_injury_at_work,hispanic_origin,hispanic_origin_name,race,race_name,non_motorist_location_at_time_of_crash,non_motorist_location_at_time_of_crash_name,timestamp_of_crash
0,48,482516,2,0,1,2,209,28,9,2,...,0,0,Not Applicable (Not A Fatality),0,Not A Fatality (Not Applicable),0,Not A Fatality (Not Applicable),11,"Non At Intersection-On Roadway, Not in Marked ...",2016-09-28 02:01:00 UTC
1,12,120582,1,0,2,1,11,7,3,9,...,0,0,Not Applicable (Not A Fatality),0,Not A Fatality (Not Applicable),0,Not A Fatality (Not Applicable),99,Unknown Location,2016-03-07 09:36:00 UTC
2,47,470412,1,0,1,1,165,13,6,99,...,0,0,Not Applicable (Not A Fatality),0,Not A Fatality (Not Applicable),0,Not A Fatality (Not Applicable),11,"Non At Intersection-On Roadway, Not in Marked ...",2016-06-13 00:00:00 UTC
3,17,170944,1,0,2,1,31,13,11,16,...,0,0,Not Applicable (Not A Fatality),0,Not A Fatality (Not Applicable),0,Not A Fatality (Not Applicable),1,At Intersection-In Marked Crosswalk,2016-11-13 16:05:00 UTC
4,37,370977,2,0,1,2,21,14,10,10,...,0,0,Not Applicable (Not A Fatality),0,Not A Fatality (Not Applicable),0,Not A Fatality (Not Applicable),11,"Non At Intersection-On Roadway, Not in Marked ...",2016-10-14 10:24:00 UTC

#### **Checking column contents to select features from 91 columns**

In [4]:
landuse_counts = df.land_use_name.value_counts()
print(landuse_counts)

Urban                                46554
Rural                                39674
Trafficway Not in State Inventory      216
Unknown                                 23
Not Reported                             7
Name: land_use_name, dtype: int64

In [5]:
func = df.functional_system_name.value_counts()
print(func)

Principal Arterial – Other                             28264
Minor Arterial                                         17539
Interstate                                             12878
Major Collector                                        11652
Local                                                   8990
Principal Arterial – Other Freeways and Expressways     4040
Minor Collector                                         2772
Trafficway Not in State Inventory                        216
Not Reported                                              91
Unknown                                                   32
Name: functional_system_name, dtype: int64

In [6]:
first_harm_ev = df.first_harmful_event_name.value_counts()
print(first_harm_ev)

Motor Vehicle in Transport                                                                                                                44709
Pedestrian                                                                                                                                13991
Rollover/Overturn                                                                                                                          5912
Tree (Standing Only)                                                                                                                       3861
Pedalcyclist                                                                                                                               1980
Curb                                                                                                                                       1790
Embankment                                                                                                                                 1544
Ditch                                                                                                                                      1440
Guardrail Face                                                                                                                             1353
Utility Pole/Light Support                                                                                                                 1054
Parked Motor Vehicle (Not In Transport)                                                                                                     966
Traffic Sign Support                                                                                                                        715
Culvert                                                                                                                                     682
Fence                                                                                                                                       672
Fell/Jumped from Vehicle                                                                                                                    607
Concrete Traffic Barrier                                                                                                                    567
Mail Box                                                                                                                                    411
Non-Motorist on Personal Conveyance                                                                                                         392
Other Post, Other Pole, or Other Support                                                                                                    386
Other Fixed Object                                                                                                                          385
Live Animal                                                                                                                                 290
Guardrail End                                                                                                                               288
Other Object (Not Fixed)                                                                                                                    287
Bridge Rail (Includes Parapet)                                                                                                              189
Cable Barrier (Since 2008)                                                                                                                  188
Bridge Pier or Support                                                                                                                      167
Railway Vehicle                                                                                                                             160
Wall                                                                                                                                        158
Ground                                                                                                                                      154
Boulder                                                                                                                                     133
Immersion (or Partial Immersion, Since 2012)                                                                                                113
Impact Attenuator/Crash Cushion                                                                                                             107
Other Traffic Barrier                                                                                                                        99
Traffic Signal Support                                                                                                                       89
Building                                                                                                                                     82
Other Non-Collision                                                                                                                          71
Motor Vehicle In-Transport Strikes or is Struck by Cargo, Persons or\nObjects Set-in-Motion from/by Another Motor Vehicle In-Transport       71
Shrubbery                                                                                                                                    69
Ridden Animal or Animal-Drawn Conveyance (Since 1998)                                                                                        50
Working Motor Vehicle                                                                                                                        46
Fire Hydrant                                                                                                                                 41
Pavement Surface Irregularity (Ruts, Potholes, Grates, etc.)                                                                                 36
Unknown                                                                                                                                      32
Cargo/Equipment Loss or Shift (Harmful to This Vehicle)                                                                                      30
Thrown or Falling Object                                                                                                                     26
Snow Bank                                                                                                                                    23
Jackknife (Harmful to This Vehicle)                                                                                                          21
Object Fell From Motor Vehicle In-Transport (Since 2013)                                                                                     11
Fire/Explosion                                                                                                                                9
Bridge Overhead Structure                                                                                                                     9
Injured in Vehicle (Non-Collision)                                                                                                            8
Name: first_harmful_event_name, dtype: int64

In [7]:
manner_of_collision_name = df.manner_of_collision_name.value_counts()
print(manner_of_collision_name)

Not Collision with Motor Vehicle in Transport (Not Necessarily in Transport for\n2005-2009)    41670
Angle                                                                                          20247
Front-to-Front                                                                                 11047
Front-to-Rear                                                                                   9104
Sideswipe – Same Direction                                                                      2092
Sideswipe – Opposite Direction                                                                  1596
Other (End-Swipes and Others)                                                                    275
Unknown                                                                                          186
Rear-to-Side                                                                                     157
Not Reported                                                                                      86
Rear-to-Rear                                                                                      14
Name: manner_of_collision_name, dtype: int64

In [8]:
vehicle_make_name = df.vehicle_make_name.value_counts()
print(vehicle_make_name.head(30))

Ford                                                                                                                                                     11711
Chevrolet                                                                                                                                                11357
Toyota                                                                                                                                                    6458
Honda                                                                                                                                                     5739
Dodge                                                                                                                                                     5216
Datsun/Nissan                                                                                                                                             3836
GMC                                                                                                                                                       2541
Harley-Davidson                                                                                                                                           2377
Jeep/Kaiser-Jeep/Willys Jeep                                                                                                                              1971
Chrysler                                                                                                                                                  1659
Hyundai                                                                                                                                                   1641
Other Make\nAuto-Union-DKW\nCarpenter\nCollins Bus\nDINA\nDivco\nHino\nMid Bus\nNeoplan\nOrion\nOshkosh\nScania\nSterling\nUD\nVan Hool\nWestern Star     1613
Freightliner                                                                                                                                              1499
Buick/Opel                                                                                                                                                1388
Kia                                                                                                                                                       1374
Pontiac                                                                                                                                                   1289
Unknown Make                                                                                                                                              1056
Suzuki                                                                                                                                                     912
Mazda                                                                                                                                                      820
Volkswagen                                                                                                                                                 792
Yamaha                                                                                                                                                     790
International Harvester/Navistar                                                                                                                           788
BMW                                                                                                                                                        764
Mercury                                                                                                                                                    763
Lexus                                                                                                                                                      728
Cadillac                                                                                                                                                   706
Saturn                                                                                                                                                     685
Volvo                                                                                                                                                      680
Peterbilt                                                                                                                                                  627
Mitsubishi                                                                                                                                                 624
Name: vehicle_make_name, dtype: int64

Looking at the top five makes involved in crashes, they are also the most common makes among vehicles owned in the US. If data could be obtained about the total registered vehicles by make in US, crash rates among different vehicles makes can be found. We will retain dummies for the top 10 makes to explore if they are more likely to be involved in crashes.

In [9]:
(df['vehicle_make_name']).describe()

count     78813
unique       67
top        Ford
freq      11711
Name: vehicle_make_name, dtype: object

In [10]:
make_model_combined = df.make_model_combined.value_counts()
print(make_model_combined)

12481.0    3675
20481.0    3152
72706.0    2300
7482.0     1975
37032.0    1631
           ...
58045.0       1
58042.0       1
9399.0        1
42422.0       1
34042.0       1
Name: make_model_combined, Length: 917, dtype: int64

In [11]:
body_type_name = df.body_type_name.value_counts()
print(body_type_name.head(15))

4-Door Sedan/Hardtop                                                            22892
Standard Pickup                                                                 10781
Compact Utility (ANSI D-16 Utility Vehicle Categories “Small” and “Midsize”)    10044
Motorcycle                                                                       5667
Large Utility (ANSI D-16 Utility Vehicle Categories “Full Size” and “Large”)     4108
2-Door Sedan/Hardtop/Coupe                                                       3427
Minivan                                                                          3368
Truck/Tractor (Cab Only, or with Any Number of Trailing Units: Any Weight)       3198
Station Wagon (Excluding Van and Truck-Based)                                    2836
Compact Pickup (Gross Vehicle Weight, GVWR, < 4,500 lbs)                         2250
Large Van – Includes Van-Based Buses                                             1259
5-Door/4-Door Hatchback                                                          1237
3-Door/2-Door Hatchback                                                           876
Unknown Body Type                                                                 873
Utility Station Wagon                                                             621
Name: body_type_name, dtype: int64

In [12]:
special_use_name = df.special_use_name.value_counts()
print(special_use_name)

No Special Use                      77277
Vehicle Used as Other Bus             691
Vehicle Used as School Transport      295
Unknown                               242
Police                                 89
Taxi                                   84
Ambulance (Since 1980)                 61
Fire Truck (Since 1982)                44
Not Reported                           15
Military                                8
Incident Response                       7
Name: special_use_name, dtype: int64

In [13]:
emergency_motor_vehicle_use = df.emergency_motor_vehicle_use.value_counts()
print(emergency_motor_vehicle_use)

Not Applicable                                                     78498
Unknown                                                              176
Emergency Operation, Emergency Warning Equipment In Use               62
Emergency Operation, Emergency Warning Equipment In Use Unknown       23
Non-Emergency Transport                                               18
Non-Emergency, Non-Transport                                          16
Not Reported                                                          14
Emergency Operation, Emergency Warning Equipment Not In Use            6
Name: emergency_motor_vehicle_use, dtype: int64

In [14]:
rollover = df.rollover.value_counts()
print(rollover)

No Rollover                            64212
Rollover, Tripped by Object/Vehicle    11663
Rollover, Untripped                     2175
Rollover, Unknown Type                   763
Name: rollover, dtype: int64

In [15]:
initial_contact_point_name = df.initial_contact_point_name.value_counts()
print(initial_contact_point_name)

Clock points                         62175
Non-Collision                         6189
Not Reported                          2622
Left                                  1582
Right                                 1464
Left-Front Side                       1074
Undercarriage                          979
Right-Front Side                       901
Unknown                                822
Left-Back Side                         364
Right-Back Side                        334
Top                                    219
Cargo/Vehicle Parts Set-In-Motion       45
Other Objects Set-In-Motion             43
Name: initial_contact_point_name, dtype: int64

In [16]:
person_type_name = df.person_type_name.value_counts()
print(person_type_name)

Driver of a Motor Vehicle In-Transport                   52399
Passenger of a Motor Vehicle In-Transport                25907
Pedestrian                                                6506
Bicyclist                                                  878
Occupant of a Motor Vehicle Not In-Transport               359
Person on Personal Conveyances (Since 2007)                186
Unknown Occupant Type in a Motor Vehicle In-Transport      148
Persons In/On Buildings (Since 2007)                        46
Occupant of a Non-Motor Vehicle Transport Device            38
Other Cyclist                                                5
Unknown Type of Non-Motorist                                 2
Name: person_type_name, dtype: int64

In [17]:
injury_severity_name = df.injury_severity_name.value_counts()
print(injury_severity_name)

Fatal Injury (K)                              37806
No Apparent Injury (O)                        21040
Suspected Minor Injury (B)                     9835
Suspected Serious Injury (A)                   8686
Possible Injury (C)                            7456
Unknown                                        1403
Injured, Severity Unknown (U) (Since 1978)      245
Died Prior to Crash                               3
Name: injury_severity_name, dtype: int64

##### **Removing 'Unknown', 'Injured, Severity Unknown (U) (Since 1978)', 'Died Prior to Crash'** 
Constitutes 1.9% of data

In [18]:
df = df[df.injury_severity_name != 'Unknown']
df = df[df.injury_severity_name != 'Injured, Severity Unknown (U) (Since 1978)']
df = df[df.injury_severity_name != 'Died Prior to Crash']

In [19]:
injury_severity_name = df.injury_severity_name.value_counts()
print(injury_severity_name)

Fatal Injury (K)                37806
No Apparent Injury (O)          21040
Suspected Minor Injury (B)       9835
Suspected Serious Injury (A)     8686
Possible Injury (C)              7456
Name: injury_severity_name, dtype: int64

In [20]:
seating_position_name = df.seating_position_name.value_counts()
print(seating_position_name)

Front Seat – Left Side (Driver's Side)                                          51235
Front Seat – Right Side                                                         13046
Not a Motor Vehicle Occupant (2005-Later)                                        7648
Second Seat – Left Side                                                          3996
Second Seat – Right Side                                                         3990
Second Seat – Middle                                                             1336
Other Passenger in Enclosed Passenger or Cargo Area (Since 2009)                 1064
Unknown                                                                           624
Not Reported                                                                      339
Front Seat – Middle                                                               272
Third Seat – Left Side                                                            253
Third Seat – Right Side                                                           248
Sleeper Section of Cab (Truck)                                                    134
Second Seat – Unknown                                                             131
Third Seat – Middle                                                               126
Riding on Vehicle Exterior                                                        100
Other Passenger in Unenclosed Passenger or Cargo Area                              79
Second Seat – Other                                                                35
Front Seat – Unknown                                                               32
Trailing Unit                                                                      30
Third Seat – Unknown                                                               30
Other Passenger in Passenger or Cargo Area, Unknown Whether Or Not\nEnclosed       27
Fourth Seat – Unknown                                                              10
Third Seat – Other                                                                  9
Fourth Seat – Middle                                                                9
Fourth Seat – Right Side                                                            6
Fourth Seat – Left Side                                                             6
Fourth Seat – Other                                                                 4
Front Seat – Other                                                                  4
Name: seating_position_name, dtype: int64

In [21]:
restraint_system_helmet_use_name = df.restraint_system_helmet_use_name.value_counts()
print(restraint_system_helmet_use_name)

Lap and Shoulder Belt Used                              43258
None Used                                               16404
Not a Motor Vehicle Occupant                             7648
Unknown                                                  5471
No Helmet                                                2810
Helmet, Unknown if DOT-Compliant                         1965
DOT-Compliant Motorcycle Helmet                          1395
Not Applicable                                           1030
Restraint Used – Type Unknown                            1016
Child Restraint Type Unknown                              873
Not Reported                                              655
Child Restraint System – Forward Facing (Since 2008)      653
Lap Belt Only Used                                        513
Booster Seat                                              274
Shoulder Belt Only Used                                   240
Child Restraint System – Rear Facing (Since 2008)         205
Helmet, Other than DOT-Compliant Motorcycle Helmet        179
Unknown if Helmet Worn                                    141
Other                                                      93
Name: restraint_system_helmet_use_name, dtype: int64

In [22]:
air_bag_deployed_name = df.air_bag_deployed_name.value_counts()
print(air_bag_deployed_name)

Not Deployed                              26295
Not Applicable                            18091
Deployed: Front                           16787
Not a Motor Vehicle Occupant               7648
Deployed: Combination                      7403
Deployed: Unknown Location                 2983
Deployment Unknown                         2471
Deployed: Side (Door, Seatback)            1618
Not Reported                               1121
Deployed: Curtain (Roof)                    339
Deployed: Other (Knee, Air Belt, etc.)       57
Switched Off                                 10
Name: air_bag_deployed_name, dtype: int64

In [23]:
ejection_name = df.ejection_name.value_counts()
print(ejection_name)

Not Ejected                              63067
Not Applicable                           13800
Totally Ejected                           5836
Partially Ejected                         1401
Not Reported                               323
Unknown if Ejected (Since 2009)            290
Ejected – Unknown Degree (Since 2008)      106
Name: ejection_name, dtype: int64

In [24]:
ejection_path_name = df.ejection_path_name.value_counts()
print(ejection_path_name)

Ejection Path Not Applicable                                                                                  77422
Ejection Path Unknown                                                                                          5490
Through Side Window (All Side Windows, Bus Side Windows)                                                        906
Through Side Door Opening (All Side Doors)                                                                      334
Other Path (e.g., Back of Pickup Truck, Torn-Off Roof, Car Cut in Half)                                         224
Through Windshield (Front Windshield Only)                                                                      155
Through Roof Opening (Sun Roof, Convertible Top Down, T-Top, Targa Top)                                         139
Through Back Window (Standard Rear Window, Back Window of Bronco,\nVan)                                         123
Through Roof (Convertible Top Up)                                                                                16
Through Back Door/Tailgate Opening (Station Wagon Tailgate, Back Door of\nTruck, Back Door of Bronco, Van)       14
Name: ejection_path_name, dtype: int64

In [25]:
extrication = df.extrication.value_counts()
print(extrication)

Not Extricated/Not Applicable    74639
Extricated                        8393
Unknown                           1791
Name: extrication, dtype: int64

In [26]:
method_of_alcohol_determination_by_police = df.method_of_alcohol_determination_by_police.value_counts()
print(method_of_alcohol_determination_by_police)

Not Reported                              70012
Evidential Test (Breath, Blood, Urine)     8951
Observed                                   4384
Preliminary Breath Test (PBT)               930
Behavioral                                  393
Passive Alcohol Sensor (PAS)                 81
Other (e.g., Saliva Test)                    72
Name: method_of_alcohol_determination_by_police, dtype: int64

In [27]:
alcohol_test_status1 = df.alcohol_test_status1.value_counts()
print(alcohol_test_status1)

Test Not Given       46469
Test Given           33359
Not Reported          3707
Unknown if Tested     1205
Test Refused            83
Name: alcohol_test_status1, dtype: int64

In [28]:
alcohol_test_status2 = df.alcohol_test_status2.value_counts()
print(alcohol_test_status2)

Not Tested for Alcohol            46552
Blood Test                        30928
Not Reported                       3878
Unknown if Tested                  1205
Preliminary Breath Test (PBT)       951
Breath Test (AC)                    431
Unknown Test Type (Since 2009)      244
Vitreous                            225
Urine                               199
Other Test Type                     121
Blood Plasma/Serum                   58
Liver                                29
Blood Clot                            2
Name: alcohol_test_status2, dtype: int64

In [29]:
alcohol_test_status3 = df.alcohol_test_status3.value_counts()
print(alcohol_test_status3)

996    46552
0      21143
995     3707
997     1248
999     1205
       ...
424        1
367        1
500        1
640        1
7          1
Name: alcohol_test_status3, Length: 442, dtype: int64

In [30]:
alcohol_test_status3_name = df.alcohol_test_status3_name.value_counts()
print(alcohol_test_status3_name)

None Given                                                46552
Actual Value of BAC Test                                  32000
Not Reported                                               3707
AC Test Performed, Results Unknown                         1248
Unknown if Tested                                          1205
PBT Positive Reading with No Actual Value (Since 2004)      111
Name: alcohol_test_status3_name, dtype: int64

These columns on alcohol are not informative on whether alcohol was the cause of the accident.

In [31]:
police_reported_drug_involvement = df.police_reported_drug_involvement.value_counts()
print(police_reported_drug_involvement)

Not Reported                 35785
No (Drugs Not Involved)      35035
Unknown (Police Reported)     9662
Yes (Drugs Involved)          4341
Name: police_reported_drug_involvement, dtype: int64

In [32]:
method_of_drug_determination_by_police = df.method_of_drug_determination_by_police.value_counts()
print(method_of_drug_determination_by_police)

Not Reported                                       74024
Evidential Test (Blood, Urine)                      6946
Other                                               3063
Behavioral                                           507
Drug Recognition Technician (DRT) Determination      283
Name: method_of_drug_determination_by_police, dtype: int64

In [33]:
drug_test_status = df.drug_test_status.value_counts()
print(drug_test_status)

Test Not Given       51278
Test Given           28019
Not Reported          4447
Unknown if Tested     1016
Test Refused            63
Name: drug_test_status, dtype: int64

In [34]:
drug_test_type1 = df.drug_test_type1.value_counts()
print(drug_test_type1)

Test Not Given                51342
Blood Test                    24850
Not Reported                   4711
Both Blood and Urine Tests     1275
Urine Test                     1107
Unknown if Tested              1016
Other Test Type                 271
Unknown Test Type               251
Name: drug_test_type1, dtype: int64

In [35]:
drug_test_type2 = df.drug_test_type2.value_counts()
print(drug_test_type2)

Test Not Given                78869
Blood Test                     5181
Both Blood and Urine Tests      361
Urine Test                      318
Other Test Type                  54
Not Reported                     23
Unknown Test Type                17
Name: drug_test_type2, dtype: int64

In [36]:
drug_test_type3 = df.drug_test_type3.value_counts()
print(drug_test_type3)

Test Not Given                82057
Blood Test                     2392
Both Blood and Urine Tests      177
Urine Test                      152
Other Test Type                  30
Not Reported                     11
Unknown Test Type                 4
Name: drug_test_type3, dtype: int64

In [37]:
drug_test_type4 = df.drug_test_type4.value_counts()
print(drug_test_type4)

0      51341
1      15523
95      4462
605     1603
997     1216
       ...
414        1
900        1
440        1
111        1
515        1
Name: drug_test_type4, Length: 103, dtype: int64

In [38]:
drug_test_type4_name = df.drug_test_type4_name.value_counts()
print(drug_test_type4_name)

Not Tested for Drugs                                    51341
No Drugs Reported/Negative                              15523
Not Reported                                             4462
Cannabinoid*                                             3512
Stimulant*                                               2692
Narcotic*                                                1669
Depressant*                                              1480
Tested for Drugs, Results Unknown                        1216
Other Drugs                                              1195
Unknown if Tested                                        1016
Tested for Drugs, Drugs Found, Type Unknown/Positive      569
Hallucinogen*                                              87
Phencyclidine (PCP) *                                      46
Inhalant*                                                  14
Name: drug_test_type4_name, dtype: int64

In [39]:
drug_test_type5_name = df.drug_test_type5_name.value_counts()
print(drug_test_type5_name)

Not Tested for Drugs                                    78922
Stimulant*                                               1790
Cannabinoid*                                             1665
Depressant*                                               879
Narcotic*                                                 736
Other Drugs                                               727
Tested for Drugs, Drugs Found, Type Unknown/Positive       39
Hallucinogen*                                              38
Phencyclidine (PCP) *                                      16
No Drugs Reported/Negative                                  8
Tested for Drugs, Results Unknown                           1
Inhalant*                                                   1
Name: drug_test_type5_name, dtype: int64

In [40]:
drug_test_type6_name = df.drug_test_type6_name.value_counts()
print(drug_test_type6_name)

Not Tested for Drugs                                    82095
Cannabinoid*                                              811
Other Drugs                                               660
Stimulant*                                                442
Depressant*                                               417
Narcotic*                                                 327
Hallucinogen*                                              28
Tested for Drugs, Drugs Found, Type Unknown/Positive       19
Phencyclidine (PCP) *                                      11
No Drugs Reported/Negative                                  6
Tested for Drugs, Results Unknown                           4
Inhalant*                                                   1
Name: drug_test_type6_name, dtype: int64

**Dropping drug columns as very large number was not tested for drugs**

In [41]:
df = df.drop(columns = ['drug_test_type4_name' , 'drug_test_type5_name', 'drug_test_type6_name'])

In [42]:
transported_to_first_treatment_facility_name = df.transported_to_first_treatment_facility_name.value_counts()
print(transported_to_first_treatment_facility_name)

Not Transported               45704
EMS Ground                    32678
EMS Air                        3750
EMS Unknown Mode               1083
Other                           604
Unknown                         278
Law Enforcement                 179
Transported Unknown Source      167
Name: transported_to_first_treatment_facility_name, dtype: int64

In [43]:
lag_hours = df.lag_hours.value_counts()
print(lag_hours)

999    49166
0      23885
1       3040
2       1059
3        616
       ...
432        1
672        1
609        1
665        1
576        1
Name: lag_hours, Length: 643, dtype: int64

In [44]:
related_factors_person_level1 = df.related_factors_person_level1.value_counts()
print(related_factors_person_level1)

0     84407
37       98
99       58
56       47
5        39
9        37
92       17
87       15
86       14
8        13
13       12
18        8
66        7
90        7
82        6
60        6
91        6
32        5
68        4
65        4
88        3
41        3
62        2
72        1
80        1
81        1
42        1
61        1
Name: related_factors_person_level1, dtype: int64

In [45]:
related_factors_person_level2 = df.related_factors_person_level2.value_counts()
print(related_factors_person_level2)

0     84759
99       58
65        2
42        1
62        1
64        1
92        1
Name: related_factors_person_level2, dtype: int64

In [46]:
related_factors_person_level3 = df.related_factors_person_level3.value_counts()
print(related_factors_person_level3)

0     84765
99       58
Name: related_factors_person_level3, dtype: int64

In [47]:
hispanic_origin_name = df.hispanic_origin_name.value_counts()
print(hispanic_origin_name)

Not A Fatality (Not Applicable)                   47017
Non-Hispanic                                      29684
Unknown                                            2867
Mexican                                            2851
Hispanic, Origin Not Specified or Other Origin     1299
Puerto Rican                                        318
European Spanish (Since 2000)                       299
Central or South American                           283
Cuban                                               205
Name: hispanic_origin_name, dtype: int64

In [48]:
race_name = df.race_name.value_counts()
print(race_name)

Not A Fatality (Not Applicable)                                              47017
White                                                                        27959
Black                                                                         5466
Unknown                                                                       2206
American Indian (Includes Aleuts and Eskimos)                                  674
All Other Races                                                                423
Chinese                                                                        157
Other Asian or Pacific Islander                                                147
Asian Indian                                                                   128
Filipino                                                                       127
Other Indian (Includes South and Central America, Since 2000)                  103
Multiple Races (Individual Races Not Specified; ex., “Mixed”, Since 2000)       98
Asian Or Pacific Islander, No Specific (Individual) Race                        81
Vietnamese                                                                      75
Korean                                                                          53
Hawaiian (Includes Part-Hawaiian)                                               47
Japanese                                                                        42
Guamanian                                                                       10
Samoan                                                                          10
Name: race_name, dtype: int64

#### **Dropping 'race' and 'hispanic origin name' columns as those are for fatalities only**

In [49]:
no_race = df.drop(columns = ['hispanic_origin_name' , 'race_name'])

In [50]:
non_motorist_location_at_time_of_crash_name = df.non_motorist_location_at_time_of_crash_name.value_counts()
print(non_motorist_location_at_time_of_crash_name)

Occupant of a Motor Vehicle (Includes Railway Train Occupants\nSince 2006)    77175
Non At Intersection-On Roadway, Not in Marked Crosswalk                        4490
At Intersection-In Marked Crosswalk                                             727
Not At Intersection-On Roadway, Crosswalk Availability Unknown                  521
Shoulder/Roadside                                                               492
At Intersection-Not in Crosswalk                                                466
At Intersection-Unmarked/Unknown If Marked Crosswalk                            199
Sidewalk                                                                        185
Non-Trafficway Area                                                             136
Unknown Location                                                                105
At Intersection-Unknown Location                                                 75
Driveway Access                                                                  55
Not At Intersection-In Marked Crosswalk                                          50
Bicycle Lane                                                                     48
Median/Crossing Island                                                           38
Not Reported                                                                     34
Parking Lane/Zone                                                                14
Other                                                                            10
Shared-Use Path                                                                   3
Name: non_motorist_location_at_time_of_crash_name, dtype: int64

In [51]:
timestamp_of_crash = df.timestamp_of_crash.value_counts()
print(timestamp_of_crash)

2016-02-13 09:28:00 UTC    117
2016-05-14 11:21:00 UTC     52
2016-09-17 14:42:00 UTC     47
2016-10-13 11:02:00 UTC     45
2016-10-23 05:16:00 UTC     44
                          ...
2016-05-29 22:37:00 UTC      1
2016-05-09 23:15:00 UTC      1
2016-04-23 14:39:00 UTC      1
2016-09-01 15:49:00 UTC      1
2016-07-05 17:33:00 UTC      1
Name: timestamp_of_crash, Length: 33025, dtype: int64

In [52]:
indication_of_misuse_of_restraint_system_helmet = df.indication_of_misuse_of_restraint_system_helmet.value_counts()
print(indication_of_misuse_of_restraint_system_helmet)

No                              76901
Not a Motor Vehicle Occupant     7648
Yes                               274
Name: indication_of_misuse_of_restraint_system_helmet, dtype: int64

In [53]:
person_number = df.person_number.value_counts()
print(person_number)

1     58494
2     15991
3      5545
4      2501
5      1016
6       423
7       203
8       115
9        71
10       50
11       40
12       31
13       28
14       24
16       21
15       21
17       19
18       17
19       17
20       15
22       13
21       13
23       11
24       11
29       10
25       10
27       10
26       10
28       10
31        9
30        9
33        8
32        8
34        7
35        5
37        4
36        4
38        4
40        3
43        3
41        3
42        3
39        3
44        2
45        1
50        1
49        1
47        1
46        1
48        1
51        1
52        1
Name: person_number, dtype: int64

In [54]:
state_number = df.state_number.value_counts()
print(state_number)

48    8829
6     8792
12    7583
13    3462
37    3130
39    2604
26    2449
42    2440
17    2405
36    2387
4     2302
1     2275
47    2249
45    2208
29    2005
18    1902
21    1878
22    1762
51    1572
40    1492
28    1442
8     1436
34    1409
55    1287
53    1274
24    1218
5     1188
41    1090
35     968
27     870
19     857
20     838
25     804
32     787
9      726
49     721
54     552
16     544
31     443
30     346
23     320
56     268
10     267
33     263
15     249
38     229
46     229
2      187
50     114
44     108
11      63
Name: state_number, dtype: int64

#### **Dropping columns without name labels and others keeping those that could inform policy**

In [55]:
data = no_race.drop(columns = ['consecutive_number', 'vehicle_number', 'number_of_motor_vehicles_in_transport_mvit', \
'person_number', 'vehicle_make', 'person_number', 'number_of_motor_vehicle_striking_non_motorist', \
'county', 'first_harmful_event', 'manner_of_collision', 'manner_of_collision_name', 'school_bus_related', \
'make_model_combined', 'first_harmful_event_name', 'functional_system', 'land_use', 'day_of_crash', \
'month_of_crash', 'hour_of_crash', 'minute_of_crash', 'month_of_crash',                        
'vehicle_trailing','special_use', 'injury_severity', 'person_type', 'emergency_motor_vehicle_use', \
'special_use_name','initial_contact_point', 'initial_contact_point_name','seating_position', 'body_type' ,\
'restraint_system_helmet_use', 'air_bag_deployed', 'ejection','ejection_path','ejection_path_name', \
'extrication', 'transported_to_first_treatment_facility', 'restraint_system_helmet_use', 'seating_position_name', 
'died_at_scene_en_route', 'method_of_alcohol_determination_by_police', 'alcohol_test_status1','alcohol_test_status2', \
'alcohol_test_status3', 'alcohol_test_status3_name', 'police_reported_drug_involvement', 'seating_position', \
'method_of_drug_determination_by_police', 'drug_test_status', 'drug_test_type1', 'drug_test_type2', \
'drug_test_type3', 'drug_test_type4', 'drug_test_type5', 'drug_test_type6','day_of_death', 'month_of_death', \
'year_of_death', 'hour_of_death', 'transported_to_first_treatment_facility_name', 'transported_to_first_treatment_facility',\
'minute_of_death', 'death_time','lag_hours', 'lag_minutes','related_factors_person_level1', \
'related_factors_person_level2', 'related_factors_person_level3', 'fatal_injury_at_work','hispanic_origin',\
'race', 'non_motorist_location_at_time_of_crash', 'rollover', 'fire_occurrence', 'non_motorist_location_at_time_of_crash_name'])

In [56]:
data.head()

,state_number,land_use_name,functional_system_name,vehicle_make_name,body_type_name,age,sex,person_type_name,injury_severity_name,restraint_system_helmet_use_name,indication_of_misuse_of_restraint_system_helmet,air_bag_deployed_name,ejection_name,police_reported_alcohol_involvement,timestamp_of_crash
1403,4,Urban,Minor Arterial,NaN,NaN,59,Female,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Unknown (Police Reported),2016-12-29 18:41:00 UTC
1404,21,Rural,Interstate,NaN,NaN,55,Male,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,No (Alcohol Not Involved),2016-09-16 18:50:00 UTC
1405,48,Urban,Principal Arterial – Other,NaN,NaN,41,Female,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Not Reported,2016-10-12 20:43:00 UTC
1406,1,Rural,Minor Arterial,NaN,NaN,59,Male,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,No (Alcohol Not Involved),2016-05-23 08:30:00 UTC
1407,6,Urban,Principal Arterial – Other,NaN,NaN,89,Female,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Unknown (Police Reported),2016-08-11 18:36:00 UTC

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 84823 entries, 1403 to 86228
Data columns (total 15 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   state_number                                     84823 non-null  int64
 1   land_use_name                                    84823 non-null  object
 2   functional_system_name                           84823 non-null  object
 3   vehicle_make_name                                77175 non-null  object
 4   body_type_name                                   77175 non-null  object
 5   age                                              84823 non-null  int64
 6   sex                                              84823 non-null  object
 7   person_type_name                                 84823 non-null  object
 8   injury_severity_name                             84823 non-null  object
 9   restraint_system_helmet_use_name                 84823 non-null  object
 10  indication_of_misuse_of_restraint_system_helmet  84823 non-null  object
 11  air_bag_deployed_name                            84823 non-null  object
 12  ejection_name                                    84823 non-null  object
 13  police_reported_alcohol_involvement              84823 non-null  object
 14  timestamp_of_crash                               84823 non-null  object
dtypes: int64(2), object(13)
memory usage: 10.4+ MB

#### **Preparing target variable**

In [58]:
data = data[data.injury_severity_name != 'Unknown']
data = data[data.injury_severity_name != 'Injured, Severity Unknown (U) (Since 1978)']
data = data[data.injury_severity_name != 'Died Prior to Crash']

In [59]:
data = data[data.sex != 'Unknown']
data = data[data.sex != 'Not Reported']

In [60]:
# data = data.restraint_system_helmet_use_name.value_counts()
# print(restraint_system_helmet_use_name)

In [61]:
data = data[data.restraint_system_helmet_use_name != 'Unknown']
data = data[data.restraint_system_helmet_use_name != 'Not Reported']
data = data[data.restraint_system_helmet_use_name != 'Unknown if Helmet Worn']
data = data[data.restraint_system_helmet_use_name != 'Other']

**Column: police reported alcohol involvement**

In [62]:
police_reported_alcohol_involvement = df.police_reported_alcohol_involvement.value_counts()
print(police_reported_alcohol_involvement)

No (Alcohol Not Involved)    35857
Not Reported                 30874
Unknown (Police Reported)     9699
Yes (Alcohol Involved)        8393
Name: police_reported_alcohol_involvement, dtype: int64

Unknown (Police reported) and Not Reported constitute almost 47% of the data. Of the remaining, alcohol was involved in only 19% of the classes. We will not include alcohol in our analysis.

In [63]:
data = data[data.land_use_name != 'Unknown']
data = data[data.land_use_name != 'Not Reported']
data = data[data.land_use_name != 'Trafficway Not in State Inventory']
data = data[data.functional_system_name != 'Unknown']
data = data[data.functional_system_name != 'Not Reported']
data = data[data.functional_system_name != 'Trafficway Not in State Inventory']

In [64]:
data['timestamp_of_crash'] = pd.to_datetime(data['timestamp_of_crash'])

In [65]:
data['day_of_week_num'] = pd.to_datetime(data['timestamp_of_crash']).dt.dayofweek

In [66]:
data['season'] = (data['timestamp_of_crash'].dt.month%12 + 3)//3

In [67]:
data.assign(session=pd.cut(data.timestamp_of_crash.dt.hour,[0,5,7,9,12,16,18,24],labels=['Night','Early Morning','Morning Peak', 'Morning', 'Afternoon','Evening Peak','Late Evening']))

,state_number,land_use_name,functional_system_name,vehicle_make_name,body_type_name,age,sex,person_type_name,injury_severity_name,restraint_system_helmet_use_name,indication_of_misuse_of_restraint_system_helmet,air_bag_deployed_name,ejection_name,police_reported_alcohol_involvement,timestamp_of_crash,day_of_week_num,season,session
1403,4,Urban,Minor Arterial,NaN,NaN,59,Female,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Unknown (Police Reported),2016-12-29 18:41:00+00:00,3,1,Evening Peak
1404,21,Rural,Interstate,NaN,NaN,55,Male,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,No (Alcohol Not Involved),2016-09-16 18:50:00+00:00,4,4,Evening Peak
1405,48,Urban,Principal Arterial – Other,NaN,NaN,41,Female,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Not Reported,2016-10-12 20:43:00+00:00,2,4,Late Evening
1406,1,Rural,Minor Arterial,NaN,NaN,59,Male,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,No (Alcohol Not Involved),2016-05-23 08:30:00+00:00,0,2,Morning Peak
1407,6,Urban,Principal Arterial – Other,NaN,NaN,89,Female,Pedestrian,Fatal Injury (K),Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Unknown (Police Reported),2016-08-11 18:36:00+00:00,3,3,Evening Peak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86224,9,Urban,Principal Arterial – Other,Mazda,"Compact Pickup (Gross Vehicle Weight, GVWR, < ...",33,Male,Driver of a Motor Vehicle In-Transport,Suspected Serious Injury (A),None Used,No,Deployed: Front,Not Ejected,Yes (Alcohol Involved),2016-04-17 20:01:00+00:00,6,2,Late Evening
86225,18,Rural,Interstate,Mazda,"Compact Pickup (Gross Vehicle Weight, GVWR, < ...",26,Male,Driver of a Motor Vehicle In-Transport,Suspected Serious Injury (A),Lap and Shoulder Belt Used,No,Not Deployed,Not Ejected,No (Alcohol Not Involved),2016-11-19 22:50:00+00:00,5,4,Late Evening
86226,30,Rural,Interstate,Mazda,"Compact Pickup (Gross Vehicle Weight, GVWR, < ...",58,Male,Driver of a Motor Vehicle In-Transport,Suspected Serious Injury (A),None Used,No,Not Applicable,Totally Ejected,Yes (Alcohol Involved),2016-04-12 02:05:00+00:00,1,2,Night
86227,45,Rural,Minor Arterial,Mazda,"Compact Pickup (Gross Vehicle Weight, GVWR, < ...",54,Male,Driver of a Motor Vehicle In-Transport,Suspected Serious Injury (A),Lap and Shoulder Belt Used,No,Deployed: Front,Not Ejected,No (Alcohol Not Involved),2016-12-02 13:45:00+00:00,4,1,Afternoon
86228,18,Rural,Local,Hyundai,4-Door Sedan/Hardtop,60,Male,Driver of a Motor Vehicle In-Transport,Suspected Serious Injury (A),Lap and Shoulder Belt Used,No,Not Deployed,Not Ejected,No (Alcohol Not Involved),2016-05-20 09:30:00+00:00,4,2,Morning Peak

In [68]:
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar

dr = pd.date_range(start='2016-01-01', end='2016-12-31')
cal = calendar()
holidays = cal.holidays(start=dr.min(), end=dr.max())

data['Holiday'] = 1 * (data['timestamp_of_crash'].isin(holidays) == True)

In [69]:
injured_dummies = pd.get_dummies(data, columns = ['injury_severity_name'])

In [70]:
injured_dummies.head()

,state_number,land_use_name,functional_system_name,vehicle_make_name,body_type_name,age,sex,person_type_name,restraint_system_helmet_use_name,indication_of_misuse_of_restraint_system_helmet,...,police_reported_alcohol_involvement,timestamp_of_crash,day_of_week_num,season,Holiday,injury_severity_name_Fatal Injury (K),injury_severity_name_No Apparent Injury (O),injury_severity_name_Possible Injury (C),injury_severity_name_Suspected Minor Injury (B),injury_severity_name_Suspected Serious Injury (A)
1403,4,Urban,Minor Arterial,NaN,NaN,59,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,Unknown (Police Reported),2016-12-29 18:41:00+00:00,3,1,0,1,0,0,0,0
1404,21,Rural,Interstate,NaN,NaN,55,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,No (Alcohol Not Involved),2016-09-16 18:50:00+00:00,4,4,0,1,0,0,0,0
1405,48,Urban,Principal Arterial – Other,NaN,NaN,41,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,Not Reported,2016-10-12 20:43:00+00:00,2,4,0,1,0,0,0,0
1406,1,Rural,Minor Arterial,NaN,NaN,59,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,No (Alcohol Not Involved),2016-05-23 08:30:00+00:00,0,2,0,1,0,0,0,0
1407,6,Urban,Principal Arterial – Other,NaN,NaN,89,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,Unknown (Police Reported),2016-08-11 18:36:00+00:00,3,3,0,1,0,0,0,0

In [71]:
injured_dummies['fatal_serious'] = injured_dummies['injury_severity_name_Fatal Injury (K)'] + injured_dummies['injury_severity_name_Suspected Serious Injury (A)']

In [72]:
injured_dummies.fatal_serious.sum()

43192

43192 out of 78054 entries are fatal_serious. My data is **balanced**!

In [73]:
injured_dummies.head()

,state_number,land_use_name,functional_system_name,vehicle_make_name,body_type_name,age,sex,person_type_name,restraint_system_helmet_use_name,indication_of_misuse_of_restraint_system_helmet,...,timestamp_of_crash,day_of_week_num,season,Holiday,injury_severity_name_Fatal Injury (K),injury_severity_name_No Apparent Injury (O),injury_severity_name_Possible Injury (C),injury_severity_name_Suspected Minor Injury (B),injury_severity_name_Suspected Serious Injury (A),fatal_serious
1403,4,Urban,Minor Arterial,NaN,NaN,59,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,2016-12-29 18:41:00+00:00,3,1,0,1,0,0,0,0,1
1404,21,Rural,Interstate,NaN,NaN,55,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,2016-09-16 18:50:00+00:00,4,4,0,1,0,0,0,0,1
1405,48,Urban,Principal Arterial – Other,NaN,NaN,41,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,2016-10-12 20:43:00+00:00,2,4,0,1,0,0,0,0,1
1406,1,Rural,Minor Arterial,NaN,NaN,59,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,2016-05-23 08:30:00+00:00,0,2,0,1,0,0,0,0,1
1407,6,Urban,Principal Arterial – Other,NaN,NaN,89,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,2016-08-11 18:36:00+00:00,3,3,0,1,0,0,0,0,1

In [74]:
new_df = injured_dummies.drop(columns = ['injury_severity_name_Fatal Injury (K)', 'injury_severity_name_No Apparent Injury (O)',\
'injury_severity_name_Possible Injury (C)', 'injury_severity_name_Suspected Minor Injury (B)', 'injury_severity_name_Suspected Serious Injury (A)'])

In [117]:
new_df.to_csv('crashdata_nodummy.csv', index = False)

This is the data for our initial machine learning model.

In [118]:
# new_df = injured_dummies.drop(columns = ['injury_severity_name_No Apparent Injury (O)',\
# 'injury_severity_name_Possible Injury (C)', 'injury_severity_name_Suspected Minor Injury (B)'])

In [119]:
# injured_dummies['fatal_serious'] = injured_dummies['injury_severity_name_Fatal Injury (K)'] + injured_dummies['injury_severity_name_Suspected Serious Injury (A)']

**Keeping the new column as target and dropping all other dummy variable columns**

In [120]:
# with_target = injured_dummies.drop(columns = ['injury_severity_name_Fatal Injury (K)', 'injury_severity_name_Suspected Serious Injury (A)'])

In [121]:
# with_target.head()

#### **Dummies for vehicle make**

In [80]:
make_dummies = pd.get_dummies(new_df, columns = ['vehicle_make_name'])

In [81]:
make_dummies.head()

,state_number,land_use_name,functional_system_name,body_type_name,age,sex,person_type_name,restraint_system_helmet_use_name,indication_of_misuse_of_restraint_system_helmet,air_bag_deployed_name,...,vehicle_make_name_Suzuki,vehicle_make_name_Thomas Built,vehicle_make_name_Toyota,vehicle_make_name_Triumph,vehicle_make_name_Unknown Make,vehicle_make_name_Victory,vehicle_make_name_Volkswagen,vehicle_make_name_Volvo,"vehicle_make_name_White/Autocar, White/GMC",vehicle_make_name_Yamaha
1403,4,Urban,Minor Arterial,NaN,59,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,0,0,0,0,0,0,0,0,0,0
1404,21,Rural,Interstate,NaN,55,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,0,0,0,0,0,0,0,0,0,0
1405,48,Urban,Principal Arterial – Other,NaN,41,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,0,0,0,0,0,0,0,0,0,0
1406,1,Rural,Minor Arterial,NaN,59,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,0,0,0,0,0,0,0,0,0,0
1407,6,Urban,Principal Arterial – Other,NaN,89,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,...,0,0,0,0,0,0,0,0,0,0

In [82]:
make = make_dummies[['state_number', 'land_use_name', 'functional_system_name', 'body_type_name', 'age', 'sex', 'person_type_name', 'restraint_system_helmet_use_name', \
'air_bag_deployed_name', 'ejection_name', 'police_reported_alcohol_involvement', 'timestamp_of_crash', 'fatal_serious', \
'vehicle_make_name_Ford', 'vehicle_make_name_Chevrolet', 'vehicle_make_name_Toyota', 'vehicle_make_name_Honda',\
'vehicle_make_name_Dodge', 'vehicle_make_name_Datsun/Nissan', 'vehicle_make_name_GMC', 'vehicle_make_name_Harley-Davidson', \
'vehicle_make_name_Jeep/Kaiser-Jeep/Willys Jeep', 'vehicle_make_name_Chrysler', 'vehicle_make_name_Freightliner', \
'vehicle_make_name_Buick/Opel', 'vehicle_make_name_Kia', 'vehicle_make_name_Pontiac', 'day_of_week_num', 'season']]
#'vehicle_make_name_Other Make\nAuto-Union-DKW\nCarpenter\nCollins Bus\nDINA\nDivco\nHino\nMid Bus\nNeoplan\nOrion\nOshkosh\nScania\nSterling\nUD\nVan Hool\nWestern Star', \ 
make.head()

,state_number,land_use_name,functional_system_name,body_type_name,age,sex,person_type_name,restraint_system_helmet_use_name,air_bag_deployed_name,ejection_name,...,vehicle_make_name_GMC,vehicle_make_name_Harley-Davidson,vehicle_make_name_Jeep/Kaiser-Jeep/Willys Jeep,vehicle_make_name_Chrysler,vehicle_make_name_Freightliner,vehicle_make_name_Buick/Opel,vehicle_make_name_Kia,vehicle_make_name_Pontiac,day_of_week_num,season
1403,4,Urban,Minor Arterial,NaN,59,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,...,0,0,0,0,0,0,0,0,3,1
1404,21,Rural,Interstate,NaN,55,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,...,0,0,0,0,0,0,0,0,4,4
1405,48,Urban,Principal Arterial – Other,NaN,41,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,...,0,0,0,0,0,0,0,0,2,4
1406,1,Rural,Minor Arterial,NaN,59,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,...,0,0,0,0,0,0,0,0,0,2
1407,6,Urban,Principal Arterial – Other,NaN,89,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,...,0,0,0,0,0,0,0,0,3,3

In [83]:
body_type_dummies = pd.get_dummies(make, columns = ['body_type_name'])

In [84]:
body_type_dummies.head()

,state_number,land_use_name,functional_system_name,age,sex,person_type_name,restraint_system_helmet_use_name,air_bag_deployed_name,ejection_name,police_reported_alcohol_involvement,...,body_type_name_Unknown Light Truck Type (Since 2013),"body_type_name_Unknown Light-Vehicle Type (Automobile, Utility Vehicle, Van or Light Truck)",body_type_name_Unknown Medium/Heavy Truck Type,body_type_name_Unknown Motored Cycle Type,body_type_name_Unknown Truck Type,body_type_name_Unknown Van Type,"body_type_name_Unknown if Single-Unit or Combination-Unit Heavy Truck (GVWR >\n26,000 lbs.)","body_type_name_Unknown if Single-Unit or Combination-Unit Medium Truck (10,000 lbs <\nGVWR < 26,000 lbs)",body_type_name_Utility Station Wagon,"body_type_name_Van-Based Bus GVWR > 10,000 lbs. (Since 2011)"
1403,4,Urban,Minor Arterial,59,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Unknown (Police Reported),...,0,0,0,0,0,0,0,0,0,0
1404,21,Rural,Interstate,55,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,No (Alcohol Not Involved),...,0,0,0,0,0,0,0,0,0,0
1405,48,Urban,Principal Arterial – Other,41,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Not Reported,...,0,0,0,0,0,0,0,0,0,0
1406,1,Rural,Minor Arterial,59,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,No (Alcohol Not Involved),...,0,0,0,0,0,0,0,0,0,0
1407,6,Urban,Principal Arterial – Other,89,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,Unknown (Police Reported),...,0,0,0,0,0,0,0,0,0,0

In [85]:
body = body_type_dummies[['state_number', 'age', 'sex', 'person_type_name', 'restraint_system_helmet_use_name', \
'air_bag_deployed_name', 'ejection_name', 'timestamp_of_crash', 'land_use_name', 'functional_system_name', 'fatal_serious', \
'vehicle_make_name_Ford', 'vehicle_make_name_Chevrolet', 'vehicle_make_name_Toyota', 'vehicle_make_name_Honda',\
'vehicle_make_name_Dodge', 'vehicle_make_name_Datsun/Nissan', 'vehicle_make_name_GMC', 'vehicle_make_name_Harley-Davidson', \
'vehicle_make_name_Jeep/Kaiser-Jeep/Willys Jeep', 'vehicle_make_name_Chrysler', \
'vehicle_make_name_Freightliner', 'vehicle_make_name_Buick/Opel', 'vehicle_make_name_Kia', \
'vehicle_make_name_Pontiac', 'body_type_name_4-Door Sedan/Hardtop', 'body_type_name_Standard Pickup',\
'body_type_name_Compact Utility (ANSI D-16 Utility Vehicle Categories “Small” and “Midsize”)', \
'body_type_name_Motorcycle', 'body_type_name_Large Utility (ANSI D-16 Utility Vehicle Categories “Full Size” and “Large”)', \
'body_type_name_2-Door Sedan/Hardtop/Coupe', 'body_type_name_Minivan', 'body_type_name_Truck/Tractor (Cab Only, or with Any Number of Trailing Units: Any Weight)', \
'body_type_name_Station Wagon (Excluding Van and Truck-Based)','body_type_name_Compact Pickup (Gross Vehicle Weight, GVWR, < 4,500 lbs)', \
'body_type_name_Large Van – Includes Van-Based Buses', 'body_type_name_5-Door/4-Door Hatchback', 'day_of_week_num', 'season']]
                         
#'vehicle_make_name_Other Make\nAuto-Union-DKW\nCarpenter\nCollins Bus\nDINA\nDivco\nHino\nMid Bus\nNeoplan\nOrion\nOshkosh\nScania\nSterling\nUD\nVan Hool\nWestern Star', \ 
body.head()

,state_number,age,sex,person_type_name,restraint_system_helmet_use_name,air_bag_deployed_name,ejection_name,timestamp_of_crash,land_use_name,functional_system_name,...,body_type_name_Large Utility (ANSI D-16 Utility Vehicle Categories “Full Size” and “Large”),body_type_name_2-Door Sedan/Hardtop/Coupe,body_type_name_Minivan,"body_type_name_Truck/Tractor (Cab Only, or with Any Number of Trailing Units: Any Weight)",body_type_name_Station Wagon (Excluding Van and Truck-Based),"body_type_name_Compact Pickup (Gross Vehicle Weight, GVWR, < 4,500 lbs)",body_type_name_Large Van – Includes Van-Based Buses,body_type_name_5-Door/4-Door Hatchback,day_of_week_num,season
1403,4,59,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,Urban,Minor Arterial,...,0,0,0,0,0,0,0,0,3,1
1404,21,55,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,Rural,Interstate,...,0,0,0,0,0,0,0,0,4,4
1405,48,41,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,Urban,Principal Arterial – Other,...,0,0,0,0,0,0,0,0,2,4
1406,1,59,Male,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,Rural,Minor Arterial,...,0,0,0,0,0,0,0,0,0,2
1407,6,89,Female,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,Urban,Principal Arterial – Other,...,0,0,0,0,0,0,0,0,3,3

#### **Dummies for gender**

In [86]:
sex = body.sex.value_counts()
print(sex)

Male      51396
Female    26658
Name: sex, dtype: int64

In [87]:
# body = body[body.sex != 'Unknown']
# body = body[body.sex != 'Not Reported']

In [88]:
gender_dummies = pd.get_dummies(body, columns = ['sex'], drop_first = True)

In [89]:
gender_dummies.head()

,state_number,age,person_type_name,restraint_system_helmet_use_name,air_bag_deployed_name,ejection_name,timestamp_of_crash,land_use_name,functional_system_name,fatal_serious,...,body_type_name_2-Door Sedan/Hardtop/Coupe,body_type_name_Minivan,"body_type_name_Truck/Tractor (Cab Only, or with Any Number of Trailing Units: Any Weight)",body_type_name_Station Wagon (Excluding Van and Truck-Based),"body_type_name_Compact Pickup (Gross Vehicle Weight, GVWR, < 4,500 lbs)",body_type_name_Large Van – Includes Van-Based Buses,body_type_name_5-Door/4-Door Hatchback,day_of_week_num,season,sex_Male
1403,4,59,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,Urban,Minor Arterial,1,...,0,0,0,0,0,0,0,3,1,0
1404,21,55,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,Rural,Interstate,1,...,0,0,0,0,0,0,0,4,4,1
1405,48,41,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,Urban,Principal Arterial – Other,1,...,0,0,0,0,0,0,0,2,4,0
1406,1,59,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,Rural,Minor Arterial,1,...,0,0,0,0,0,0,0,0,2,1
1407,6,89,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,Urban,Principal Arterial – Other,1,...,0,0,0,0,0,0,0,3,3,0

#### **Dummies for state**

In [90]:
state_dummies = pd.get_dummies(gender_dummies, columns = ['state_number'])

In [91]:
state_dummies.head()

,age,person_type_name,restraint_system_helmet_use_name,air_bag_deployed_name,ejection_name,timestamp_of_crash,land_use_name,functional_system_name,fatal_serious,vehicle_make_name_Ford,...,state_number_46,state_number_47,state_number_48,state_number_49,state_number_50,state_number_51,state_number_53,state_number_54,state_number_55,state_number_56
1403,59,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,Urban,Minor Arterial,1,0,...,0,0,0,0,0,0,0,0,0,0
1404,55,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,Rural,Interstate,1,0,...,0,0,0,0,0,0,0,0,0,0
1405,41,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,Urban,Principal Arterial – Other,1,0,...,0,0,1,0,0,0,0,0,0,0
1406,59,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,Rural,Minor Arterial,1,0,...,0,0,0,0,0,0,0,0,0,0
1407,89,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,Urban,Principal Arterial – Other,1,0,...,0,0,0,0,0,0,0,0,0,0

In [92]:
state_dummies = state_dummies[['age', 'sex_Male', 'person_type_name', 'restraint_system_helmet_use_name', \
'air_bag_deployed_name', 'land_use_name', 'functional_system_name', 'ejection_name', 'timestamp_of_crash', 'fatal_serious', \
'vehicle_make_name_Ford', 'vehicle_make_name_Chevrolet', 'vehicle_make_name_Toyota', 'vehicle_make_name_Honda',\
'vehicle_make_name_Dodge', 'vehicle_make_name_Datsun/Nissan', 'vehicle_make_name_GMC', 'vehicle_make_name_Harley-Davidson', \
'vehicle_make_name_Jeep/Kaiser-Jeep/Willys Jeep', 'vehicle_make_name_Chrysler', \
'vehicle_make_name_Freightliner', 'vehicle_make_name_Buick/Opel', 'vehicle_make_name_Kia', \
'vehicle_make_name_Pontiac', 'body_type_name_4-Door Sedan/Hardtop', 'body_type_name_Standard Pickup',\
'body_type_name_Compact Utility (ANSI D-16 Utility Vehicle Categories “Small” and “Midsize”)', \
'body_type_name_Motorcycle', 'body_type_name_Large Utility (ANSI D-16 Utility Vehicle Categories “Full Size” and “Large”)', \
'body_type_name_2-Door Sedan/Hardtop/Coupe', 'body_type_name_Minivan', 'body_type_name_Truck/Tractor (Cab Only, or with Any Number of Trailing Units: Any Weight)', \
'body_type_name_Station Wagon (Excluding Van and Truck-Based)','body_type_name_Compact Pickup (Gross Vehicle Weight, GVWR, < 4,500 lbs)', \
'body_type_name_Large Van – Includes Van-Based Buses', 'body_type_name_5-Door/4-Door Hatchback', \
'state_number_48', 'state_number_6', 'state_number_12', 'state_number_13', 'state_number_37', \
'state_number_39', 'state_number_26', 'state_number_42', 'state_number_17', 'state_number_36', \
'state_number_4', 'state_number_1', 'day_of_week_num', 'season']]

In [93]:
state_dummies.head()

,age,sex_Male,person_type_name,restraint_system_helmet_use_name,air_bag_deployed_name,land_use_name,functional_system_name,ejection_name,timestamp_of_crash,fatal_serious,...,state_number_37,state_number_39,state_number_26,state_number_42,state_number_17,state_number_36,state_number_4,state_number_1,day_of_week_num,season
1403,59,0,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Urban,Minor Arterial,Not Applicable,2016-12-29 18:41:00+00:00,1,...,0,0,0,0,0,0,1,0,3,1
1404,55,1,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Rural,Interstate,Not Applicable,2016-09-16 18:50:00+00:00,1,...,0,0,0,0,0,0,0,0,4,4
1405,41,0,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Urban,Principal Arterial – Other,Not Applicable,2016-10-12 20:43:00+00:00,1,...,0,0,0,0,0,0,0,0,2,4
1406,59,1,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Rural,Minor Arterial,Not Applicable,2016-05-23 08:30:00+00:00,1,...,0,0,0,0,0,0,0,1,0,2
1407,89,0,Pedestrian,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Urban,Principal Arterial – Other,Not Applicable,2016-08-11 18:36:00+00:00,1,...,0,0,0,0,0,0,0,0,3,3

#### **Dummies for person_type**

In [94]:
person_type_dummies = pd.get_dummies(state_dummies, columns = ['person_type_name'], drop_first = True)

In [95]:
person_type_dummies.head()

,age,sex_Male,restraint_system_helmet_use_name,air_bag_deployed_name,land_use_name,functional_system_name,ejection_name,timestamp_of_crash,fatal_serious,vehicle_make_name_Ford,...,person_type_name_Driver of a Motor Vehicle In-Transport,person_type_name_Occupant of a Motor Vehicle Not In-Transport,person_type_name_Occupant of a Non-Motor Vehicle Transport Device,person_type_name_Other Cyclist,person_type_name_Passenger of a Motor Vehicle In-Transport,person_type_name_Pedestrian,person_type_name_Person on Personal Conveyances (Since 2007),person_type_name_Persons In/On Buildings (Since 2007),person_type_name_Unknown Occupant Type in a Motor Vehicle In-Transport,person_type_name_Unknown Type of Non-Motorist
1403,59,0,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Urban,Minor Arterial,Not Applicable,2016-12-29 18:41:00+00:00,1,0,...,0,0,0,0,0,1,0,0,0,0
1404,55,1,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Rural,Interstate,Not Applicable,2016-09-16 18:50:00+00:00,1,0,...,0,0,0,0,0,1,0,0,0,0
1405,41,0,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Urban,Principal Arterial – Other,Not Applicable,2016-10-12 20:43:00+00:00,1,0,...,0,0,0,0,0,1,0,0,0,0
1406,59,1,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Rural,Minor Arterial,Not Applicable,2016-05-23 08:30:00+00:00,1,0,...,0,0,0,0,0,1,0,0,0,0
1407,89,0,Not a Motor Vehicle Occupant,Not a Motor Vehicle Occupant,Urban,Principal Arterial – Other,Not Applicable,2016-08-11 18:36:00+00:00,1,0,...,0,0,0,0,0,1,0,0,0,0

#### **Restraint_Helmet**

In [96]:
restraint = person_type_dummies.restraint_system_helmet_use_name.value_counts()
print(restraint_system_helmet_use_name)

Lap and Shoulder Belt Used                              43258
None Used                                               16404
Not a Motor Vehicle Occupant                             7648
Unknown                                                  5471
No Helmet                                                2810
Helmet, Unknown if DOT-Compliant                         1965
DOT-Compliant Motorcycle Helmet                          1395
Not Applicable                                           1030
Restraint Used – Type Unknown                            1016
Child Restraint Type Unknown                              873
Not Reported                                              655
Child Restraint System – Forward Facing (Since 2008)      653
Lap Belt Only Used                                        513
Booster Seat                                              274
Shoulder Belt Only Used                                   240
Child Restraint System – Rear Facing (Since 2008)         205
Helmet, Other than DOT-Compliant Motorcycle Helmet        179
Unknown if Helmet Worn                                    141
Other                                                      93
Name: restraint_system_helmet_use_name, dtype: int64

In [97]:
person_type_dummies = person_type_dummies[person_type_dummies.restraint_system_helmet_use_name != 'Unknown']
person_type_dummies = person_type_dummies[person_type_dummies.restraint_system_helmet_use_name != 'Not Reported']
person_type_dummies = person_type_dummies[person_type_dummies.restraint_system_helmet_use_name != 'Unknown if Helmet Worn']
person_type_dummies = person_type_dummies[person_type_dummies.restraint_system_helmet_use_name != 'Other']

In [98]:
restraint_helmet_dummies = pd.get_dummies(person_type_dummies, columns = ['restraint_system_helmet_use_name'], drop_first = True)

In [99]:
restraint_helmet_dummies.head()

,age,sex_Male,air_bag_deployed_name,land_use_name,functional_system_name,ejection_name,timestamp_of_crash,fatal_serious,vehicle_make_name_Ford,vehicle_make_name_Chevrolet,...,"restraint_system_helmet_use_name_Helmet, Other than DOT-Compliant Motorcycle Helmet","restraint_system_helmet_use_name_Helmet, Unknown if DOT-Compliant",restraint_system_helmet_use_name_Lap Belt Only Used,restraint_system_helmet_use_name_Lap and Shoulder Belt Used,restraint_system_helmet_use_name_No Helmet,restraint_system_helmet_use_name_None Used,restraint_system_helmet_use_name_Not Applicable,restraint_system_helmet_use_name_Not a Motor Vehicle Occupant,restraint_system_helmet_use_name_Restraint Used – Type Unknown,restraint_system_helmet_use_name_Shoulder Belt Only Used
1403,59,0,Not a Motor Vehicle Occupant,Urban,Minor Arterial,Not Applicable,2016-12-29 18:41:00+00:00,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1404,55,1,Not a Motor Vehicle Occupant,Rural,Interstate,Not Applicable,2016-09-16 18:50:00+00:00,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1405,41,0,Not a Motor Vehicle Occupant,Urban,Principal Arterial – Other,Not Applicable,2016-10-12 20:43:00+00:00,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1406,59,1,Not a Motor Vehicle Occupant,Rural,Minor Arterial,Not Applicable,2016-05-23 08:30:00+00:00,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1407,89,0,Not a Motor Vehicle Occupant,Urban,Principal Arterial – Other,Not Applicable,2016-08-11 18:36:00+00:00,1,0,0,...,0,0,0,0,0,0,0,1,0,0

In [100]:
# restraint_helmet_dummies = restraint_helmet_dummies[restraint_helmet_dummies.land_use_name != 'Unknown']
# restraint_helmet_dummies = restraint_helmet_dummies[restraint_helmet_dummies.land_use_name != 'Not Reported']
# restraint_helmet_dummies = restraint_helmet_dummies[restraint_helmet_dummies.land_use_name != 'Trafficway Not in State Inventory']
# restraint_helmet_dummies = restraint_helmet_dummies[restraint_helmet_dummies.functional_system_name != 'Unknown']
# restraint_helmet_dummies = restraint_helmet_dummies[restraint_helmet_dummies.functional_system_name != 'Not Reported']
# restraint_helmet_dummies = restraint_helmet_dummies[restraint_helmet_dummies.functional_system_name != 'Trafficway Not in State Inventory']

In [101]:
landuse_functional = pd.get_dummies(restraint_helmet_dummies, columns = ['land_use_name', 'functional_system_name'], drop_first = True)

In [102]:
landuse_functional.head()

,age,sex_Male,air_bag_deployed_name,ejection_name,timestamp_of_crash,fatal_serious,vehicle_make_name_Ford,vehicle_make_name_Chevrolet,vehicle_make_name_Toyota,vehicle_make_name_Honda,...,restraint_system_helmet_use_name_Not a Motor Vehicle Occupant,restraint_system_helmet_use_name_Restraint Used – Type Unknown,restraint_system_helmet_use_name_Shoulder Belt Only Used,land_use_name_Urban,functional_system_name_Local,functional_system_name_Major Collector,functional_system_name_Minor Arterial,functional_system_name_Minor Collector,functional_system_name_Principal Arterial – Other,functional_system_name_Principal Arterial – Other Freeways and Expressways
1403,59,0,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,1,0,0,0,0,...,1,0,0,1,0,0,1,0,0,0
1404,55,1,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1405,41,0,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,1,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
1406,59,1,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1407,89,0,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,1,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0

In [103]:
# landuse_functional['timestamp_of_crash'] = pd.to_datetime(landuse_functional['timestamp_of_crash'])

In [104]:
# landuse_functional['day_of_week_num'] = pd.to_datetime(landuse_functional['timestamp_of_crash']).dt.dayofweek

In [105]:
daysofweek = pd.get_dummies(landuse_functional, columns = ['day_of_week_num'], drop_first = True)

In [106]:
daysofweek.head()

,age,sex_Male,air_bag_deployed_name,ejection_name,timestamp_of_crash,fatal_serious,vehicle_make_name_Ford,vehicle_make_name_Chevrolet,vehicle_make_name_Toyota,vehicle_make_name_Honda,...,functional_system_name_Minor Arterial,functional_system_name_Minor Collector,functional_system_name_Principal Arterial – Other,functional_system_name_Principal Arterial – Other Freeways and Expressways,day_of_week_num_1,day_of_week_num_2,day_of_week_num_3,day_of_week_num_4,day_of_week_num_5,day_of_week_num_6
1403,59,0,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1404,55,1,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1405,41,0,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1406,59,1,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1407,89,0,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0

In [107]:
# daysofweek['season'] = (daysofweek['timestamp_of_crash'].dt.month%12 + 3)//3

In [108]:
# daysofweek

In [109]:
# daysofweek.fatal_serious.sum()`

In [110]:
season = pd.get_dummies(daysofweek, columns = ['season'], drop_first = True)

In [111]:
season.head()

,age,sex_Male,air_bag_deployed_name,ejection_name,timestamp_of_crash,fatal_serious,vehicle_make_name_Ford,vehicle_make_name_Chevrolet,vehicle_make_name_Toyota,vehicle_make_name_Honda,...,functional_system_name_Principal Arterial – Other Freeways and Expressways,day_of_week_num_1,day_of_week_num_2,day_of_week_num_3,day_of_week_num_4,day_of_week_num_5,day_of_week_num_6,season_2,season_3,season_4
1403,59,0,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1404,55,1,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1405,41,0,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1406,59,1,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1407,89,0,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86224,33,1,Deployed: Front,Not Ejected,2016-04-17 20:01:00+00:00,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
86225,26,1,Not Deployed,Not Ejected,2016-11-19 22:50:00+00:00,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
86226,58,1,Not Applicable,Totally Ejected,2016-04-12 02:05:00+00:00,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
86227,54,1,Deployed: Front,Not Ejected,2016-12-02 13:45:00+00:00,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
86228,60,1,Not Deployed,Not Ejected,2016-05-20 09:30:00+00:00,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [112]:
# timestamp = season.timestamp_of_crash.value_counts
# print(timestamp_of_crash)

2016-02-13 09:28:00 UTC    117
2016-05-14 11:21:00 UTC     52
2016-09-17 14:42:00 UTC     47
2016-10-13 11:02:00 UTC     45
2016-10-23 05:16:00 UTC     44
                          ...
2016-05-29 22:37:00 UTC      1
2016-05-09 23:15:00 UTC      1
2016-04-23 14:39:00 UTC      1
2016-09-01 15:49:00 UTC      1
2016-07-05 17:33:00 UTC      1
Name: timestamp_of_crash, Length: 33025, dtype: int64

In [113]:
# season.assign(session=pd.cut(season.timestamp_of_crash.dt.hour,[0,5,7,9,12,16,18,24],labels=['Night','Early Morning','Morning Peak', 'Morning', 'Afternoon','Evening Peak','Late Evening']))

In [114]:
# from pandas.tseries.holiday import USFederalHolidayCalendar as calendar

# dr = pd.date_range(start='2016-01-01', end='2016-12-31')
# cal = calendar()
# holidays = cal.holidays(start=dr.min(), end=dr.max())

# season['Holiday'] = 1 * (season['timestamp_of_crash'].isin(holidays) == True)

In [115]:
season

,age,sex_Male,air_bag_deployed_name,ejection_name,timestamp_of_crash,fatal_serious,vehicle_make_name_Ford,vehicle_make_name_Chevrolet,vehicle_make_name_Toyota,vehicle_make_name_Honda,...,day_of_week_num_1,day_of_week_num_2,day_of_week_num_3,day_of_week_num_4,day_of_week_num_5,day_of_week_num_6,season_2,season_3,season_4,Holiday
1403,59,0,Not a Motor Vehicle Occupant,Not Applicable,2016-12-29 18:41:00+00:00,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1404,55,1,Not a Motor Vehicle Occupant,Not Applicable,2016-09-16 18:50:00+00:00,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1405,41,0,Not a Motor Vehicle Occupant,Not Applicable,2016-10-12 20:43:00+00:00,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1406,59,1,Not a Motor Vehicle Occupant,Not Applicable,2016-05-23 08:30:00+00:00,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1407,89,0,Not a Motor Vehicle Occupant,Not Applicable,2016-08-11 18:36:00+00:00,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86224,33,1,Deployed: Front,Not Ejected,2016-04-17 20:01:00+00:00,1,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
86225,26,1,Not Deployed,Not Ejected,2016-11-19 22:50:00+00:00,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
86226,58,1,Not Applicable,Totally Ejected,2016-04-12 02:05:00+00:00,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
86227,54,1,Deployed: Front,Not Ejected,2016-12-02 13:45:00+00:00,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
86228,60,1,Not Deployed,Not Ejected,2016-05-20 09:30:00+00:00,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0

In [116]:
season.to_csv('crashdata.csv', index = False)